dist: trusty
sudo: required
language: cpp
compiler:
- gcc
- clang

os:
- linux
- osx

osx_image: xcode8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - doxygen
    - graphviz

env:
  global:
  - PATH=$HOME/_cmake/bin:$HOME/miniconda/bin:$PATH
  - MACOSX_DEPLOYMENT_TARGET=10.7

  matrix:
  # - python=2.7 CONDA_PY=27
  - python=3.5 CONDY_PY=35

matrix:
  exclude:
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc

cache:
  apt: true
  ccache: true

before_install:
- tools/ci/travis/setup_travis.sh
- tools/ci/travis/install_miniconda.sh

install:
- if [ "$CXX" = "g++" ]; then export CXX="/usr/lib/ccache/g++-5" CC="/usr/lib/ccache/gcc-5"; fi
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export BUILD_TYPE="RelWithDebInfo"; else export BUILD_TYPE="Release"; fi

script:
- conda build -q tools/conda-recipe

after_success:
- tools/ci/travis/upload_conda_package.sh
- tools/ci/travis/make_docs.sh

notifications:
  email: false
