sudo: false
language: cpp
compiler:
  - gcc
  - clang
os:
 - linux
 - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - clang-3.7
    - g++-5
    - gcc-5

env:
  global:
    - PATH=$HOME/_cmake/bin:$HOME/miniconda/bin:$PATH
  matrix:
    - python=2.7
      CONDA_PY=27
    - python=3.5
      CONDY_PY=35

before_install:
- tools/ci/travis/setup_travis.sh
- tools/ci/travis/install_miniconda.sh
- conda config --set always_yes true
- conda config --add channels omnia
- conda install -q conda-build

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="/usr/bin/clang++-3.7" CC="/usr/bin/clang-3.7"; fi

script:
- conda build -q tools/conda-recipe
