dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
  - clang
os:
 - linux
 - osx

osx_image: beta-xcode6.1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5

env:
  global:
    - PATH=$HOME/_cmake/bin:$HOME/miniconda/bin:$PATH
    - MACOSX_DEPLOYMENT_TARGET=10.7
    - LLVM_VERSION=3.7.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
  matrix:
    - python=2.7
      CONDA_PY=27
    - python=3.5
      CONDY_PY=35

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

cache:
  apt: true
  directories:
    - $HOME/readdy_cache/boost_dl_job_1
    - $HOME/readdy_cache/boost_dl_job_2
    - $HOME/readdy_cache/boost_dl_job_3
    - $HOME/readdy_cache/boost_dl_job_4

before_install:
- wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
- mkdir $HOME/clang+llvm
- tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
- export PATH=$HOME/clang+llvm/bin:$PATH
- tools/ci/travis/setup_travis.sh
- tools/ci/travis/install_miniconda.sh
- export BOOST_DOWNLOAD_CACHE_DIR=$HOME/readdy_cache/boost_dl_job_${TRAVIS_JOB_NUMBER##*.}

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
- conda build -q tools/conda-recipe

notifications:
  email: false