environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\ci\\appveyor\\run_with_env.cmd"
    CONDA_NPY: "110"

  matrix:
    - PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"

    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "34"
      ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;"

  - conda config --set always_yes true