environment:
  global:
    CONDA_NPY: "110"
    TRAVIS: "0"
    BOOST_DOWNLOAD_CACHE_DIR: "C:\\boost_cache"

  matrix:
    - MINICONDA_PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"

    - MINICONDA_PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      ARCH: "64"

    - MINICONDA_PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"

    - MINICONDA_PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "34"
      ARCH: "64"

install:
  - "SET PATH=%MINICONDA_PYTHON%;%MINICONDA_PYTHON%\\Scripts;%PATH%;"

  - conda config --set always_yes true
  - conda install -q conda-build

build: false

test_script:
  - conda build -q tools/conda-recipe