package:
  name: readdy
  version: 0.1
source:
  path: ../..

build:
  script_env:
    - CXX
    - CC
    - BOOST_DOWNLOAD_CACHE_DIR
    - TRAVIS
  rpaths:
    - lib/
    - readdy/readdy_plugins/

requirements:
  build:
    - cmake >=3.2.0
    - curl
    - python
    - hdf5 ==1.8.15.1 # [osx]
    - hdf5 >=1.8.15.1 # [not osx]
    - bzip2
    - numpy

  run:
    - python
    - numpy
    - hdf5 ==1.8.15.1 # [osx]
    - hdf5 >=1.8.15.1 # [not osx]

test:
  requires:
    - python
    - numpy
    - ipython
    - nose
    - hdf5 ==1.8.15.1 # [osx]
    - hdf5 >=1.8.15.1 # [not osx]
