package:
  name: readdy2
  version: 0.1
source:
  path: ../..

build:
  script_env:
    - CXX
    - CC

requirements:
  build:
    - boost >=1.58
  run:
    - boost >=1.58

test:
  requires:
    - python
    - boost >=1.58