package:
  name: readdy2
  version: 0.1
source:
  path: ../..

build:
  script_env:
    - CXX
    - CC
    - READDY_INSTALL_UNIT_TEST_EXECUTABLE
    - BOOST_DOWNLOAD_CACHE_DIR

requirements:
  build:
    - cmake >=3.2.0
    - curl
#  run:
#    - boost 1.59.0

#test:
#  requires:
#    - boost 1.59.0
