package:
  name: readdy
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}
source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

  script_env:
    - CXX
    - CC
    - TRAVIS
  rpaths:
    - lib/
    - readdy/readdy_plugins/

requirements:
  build:
    - cmake >=3.2.0
    - curl
    - python
    - hdf5 ==1.8.15.1 # [osx]
    - hdf5 >=1.8.15.1 # [not osx]
    - bzip2
    - numpy

  run:
    - python
    - numpy
    - hdf5 ==1.8.15.1 # [osx]
    - hdf5 >=1.8.15.1 # [not osx]
    - vs2015_runtime  # [win]

test:
  requires:
    - python
    - numpy
    - ipython
    - nose
    - hdf5 ==1.8.15.1 # [osx]
    - hdf5 >=1.8.15.1 # [not osx]
