package:
  name: readdy2
  version: 0.1
source:
  path: ../..

build:
  script_env:
    - CXX
    - CC
    - READDY_INSTALL_UNIT_TEST_EXECUTABLE

requirements:
  build:
    - boost ==1.58
  run:
    - boost ==1.58

test:
  requires:
    - boost ==1.58
