package:
  name: readdy2
  version: 0.1
source:
  path: ../..

build:
  script_env:
    - CXX
    - CC
    - READDY_INSTALL_UNIT_TEST_EXECUTABLE

requirements:
  build:
    - boost 1.59.0 # [not osx]
    - cmake >=3.2.0
  run:
    - boost 1.59.0 # [not osx]

test:
  requires:
    - boost 1.59.0 # [not osx]
