package:
  name: readdy
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}
source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CXX
    - CC
    - TRAVIS
    - BUILD_TYPE
  rpaths:
    - lib/
    - readdy/readdy_plugins/

requirements:
  build:
    - cmake # [not win]
    - python
    - h5py
    - hdf5
    - bzip2
    - numpy
    - zlib 1.2.*
    - vs2015_runtime  # [win]

  run:
    - python
    - numpy
    - h5py
    - progress_reporter
    - pint
    - hdf5
    - networkx
    - matplotlib
    - zlib 1.2.*
    - libgcc
    - vs2015_runtime  # [win]

test:
  requires:
    - nose
