package:
  name: readdy2
  version: 0.1
source:
  path: ../..

build:
  script_env:
    - CXX
    - CC
    - READDY_INSTALL_UNIT_TEST_EXECUTABLE
    - BOOST_DOWNLOAD_CACHE_DIR
    - TRAVIS

requirements:
  build:
    - cmake >=3.2.0
    - curl
    - python

  run:
    - python

test:
  requires:
    - python
